name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Change Directory
      run: cd ${{github.workspace}}/UTD

    - name: Configure CMake MacOS, Ubuntu
      if: "${{ contains(matrix.os, 'macos-latest') || contains(matrix.os, 'ubuntu-latest')}}"
      run: cmake -S ${{github.workspace}}/UTD

    - name: Configure CMake Windows
      if: "${{ contains(matrix.os, 'windows-latest')}}"
      run: cmake -S ${{github.workspace}}\UTD

    - name: Build MacOS
      if: "${{ contains(matrix.os, 'macos-latest') || contains(matrix.os, 'ubuntu-latest')}}"
      run: make

    - name: Build Windows
      if: "${{ contains(matrix.os, 'windows-latest')}}"
      run: nmake

    - name: Test 
      run: ./main_test 
