name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Change Directory
      run: cd ${{github.workspace}}/UTD
    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/UTD
    - name: Build
      run: make
    - name: Test 
      run: ./main_test 
